### PR TITLE
Initial ALP logo based on Franken alps

### PR DESCRIPTION
**Pull request by lkocman**
* Logo is copying shape of alps as visualised on
  RITTER EPPELEIN VON GAILINGEN DER FURCHTBARE RAUBRITTER IN FRANKEN, VOLUME 1
  by Johann Friederich Stettner

* This logo maps individual layers on top of baseos up to the worload (vm, container, app ...)

### CODE REVIEW

**Comment by lkocman** [comment]
Original shape
4127mCU2vEL _SX382_BO1,204,203,200_


Progress
progress

**Comment by lkocman** [comment]
opensuse-alp-logo

Actual logo concept which reflects individual layers baseOS, hypervisor, container, workload and it mirrors Franken Alps as a tribute to SUSE's origin

Idea is stolen from the ALP Product Management t-shirts (I believe they had three lines making a hill shape) but I've added the Franken aspect

**Comment by lkocman** [comment]
I dis use colors from https://en.opensuse.org/openSUSE:Artwork_brand

two primary and then the optional blue with different opacities from the enlisted values.

**Comment by lkocman** [comment]
if the concept is okay-ish, I'd probably add spacing in between opensuse the logo part

**Comment by javierllorente** [comment]
I like the idea of different building blocks. 
Gecko + Franken Alps = two logos. Not sure if I would the Gecko in this case. If we follow other styles (Tumbleweed, Leap), there is no Gecko and sometimes not even "openSUSE".
As you already said, it needs more space between the building blocks and the letters. I would add playing with the logo's size (smaller).

**Comment by lkocman** [comment]
@hellcp wow the first one is awesome!!!!

**Comment by tacerus** [comment]
I would like a Geeko to be climbing @hellcp's alps.

**Comment by knurpht** [comment]
I prefer the middle one. For my eyes it's more balanced

**Comment by hellcp** [comment]
We tend to use a single colour (no idea what colour, would need to see what looks best), but I don't have anything against multiple colours if that fits the concept better, kinda requires a bit more prototyping :P

**Comment by lkocman** [comment]
concept

How about this? :-)

**Comment by lkocman** [comment]
concept

even more minimal approach

**Comment by knurpht** [comment]
I like the top one, though wonder if black would go in dark mode

**Comment by hellcp** [comment]
They have problems in both dark and light mode tbh

**Comment by ddemaio** [comment]
excellent @hellcp I really like the vision and look.

**Comment by jlausuch** [comment]
> > Gecko + Franken Alps = two logos. Not sure if I would the Gecko in this case. If we follow other styles (Tumbleweed, Leap), there is no Gecko and sometimes not even "openSUSE".
> 
> We do [this](https://github.com/openSUSE/distribution-logos/blob/main/Tumbleweed/light-dual-branding.svg) if we need to include both logos, we don't combine the logos the way you did above, it's too much stuff.
> 
> I did a quick prototype of this concept with the style we use for our prototype distribution logos, look if there's anything here that catches your eye, and feel free to give feedback for any possible improvements Screenshot from 2022-06-16 19-18-55

The second one reminds of sports equipment brand, but upside down :) 
https://d1011j0lbv5k1u.cloudfront.net/assets/store-527456/527456-logo-1617177153.jpg

**Comment by jlausuch** [comment]
> concept
> 
> concept
> 
> concept
> 
> even more minimal approach

I like 3rd one. Can we somehow have the horizontal lines shorter and closer to each other? to give more the feeling of a step mountain, similar to what @hellcp proposed

**Comment by lkocman** [comment]
opensuse-alp-logo

**Comment by lkocman** [comment]
opensuse-alp-logo-colors

making it more vivid :-) the orange is from the default scale in inkscape

**Comment by hellcp** [comment]
Those colours most definitely clash, especially blue with cyan (not to mention it looks like the exact same shade as Tumbleweed)

**Comment by lkocman** [comment]
Would you say then just white and use either blue, cyan, green (our palette) as bg?

**Comment by jlausuch** [comment]
Was thinking of making it narrower. 
image

I kind of like the all-white version, without colors (except the background blue, which fits very nice with the white from the logo).

**Comment by hellcp** [comment]
I don't really see the need to limit ourselves to our palette, it is quite limited, and we do extend it with Leap, Leap Micro and MicroOS colours already

**Comment by asmorodskyi** [comment]
just after fast scroll -  majority of pictures looks more like ship with  2 decks than mountains ...

**Comment by lilfrogg** [comment]
One thing thatÄs probably worth keeping in mind is that the "linux distribution with a mountain theme" space is already quite busy. There is Rocky Linux:
https://external-content.duckduckgo.com/iu/?u=https%3A%2F%2Ftse2.mm.bing.net%2Fth%3Fid%3DOIP.7zBEWfteMYq2CjZF6mTuCQHaFj%26pid%3DApi&f=1
and Alpine Linux:
https://external-content.duckduckgo.com/iu/?u=https%3A%2F%2Ftse1.mm.bing.net%2Fth%3Fid%3DOIP.f465wfgYEzQ_tcoxYWU1NgHaE0%26pid%3DApi&f=1

might be even more. So I think a good idea would be to make sure ALP stays distinct from those both in terms of colour and shape.

**Comment by hellcp** [comment]
Made a sheet with these logos with the typical usage scenario, just so you can tell how we use these logos typically (also added cool blue to my variants to see how they look with that)
light-dual-branding

What I do want to indicate is that we use a consistent line width for all the distros using the new logos, just to make them appear as crisp as possible. That means that when you remove the lines from the bottom or the top, the logo becomes significantly smaller. In isolation that's not much of an issue, it only really becomes one when you try to fit the logo into our existing branding

**Comment by lilfrogg** [comment]
Also personally, I'd stick to four layers or less for the logo. Five or more seems a bit too complicated imo. Also some of the wider/many layered logos look a bit like the Disney logo to me. Not sure whether I'm the only one with that association.

http://uzerfriendly.com/wp-content/uploads/2014/03/Walt-Disney-Screencaps-The-Walt-Disney-Logo-walt-disney-characters-31872968-2560-1440.jpg

**Comment by lilfrogg** [comment]
Slightly different concept:
alp1
alp2

Was trying to combine the letters A L P into one logo. A is on top, L bottom left, and P on the right. The round pard of the P can be interpreted as the sun/moon being partially occluded by the mountain.

**Comment by lilfrogg** [comment]
Slightly adjusted version of previous logo:
alp2

One thing that might be a bit of an issue with that logo is that the order of the letter probably reads a bit more like "LAP" than "ALP". Although I personally don't think it's the biggest of issues, as you probably won't see the letters at first glance anyways and have to somewhat "find" them anyways, at which point order isn't super important anymore anyways.

Also tried to do a few more versions where the letters are strictly ordered left to right, but I'm not super happy with any of these versions and think the compact original version looks a lot better.

 
alp3
alp35
alp4
alp5
9771/174439341-54794c68-b14f-4779-b9ee-4aa14dc03633.jpg)

**Comment by hellcp** [comment]
> It doesn't just rely on people making the mental connection to Franken Alps (as some people such as myself might think of "mountain" before thinking of "alps"). It also incorporates the ALP letters so that people can more quickly pick up that this is supposed to represent ALP.

Yeah, but we aren't making a logo for franken alps, the fact it's not the first association people have is a great thing, because it means people can associate whatever we end up with as the alp logo and alp logo only. The reference to a real life object of location is a form of an easter egg, a fun fact that makes people appreciate the thought that went into the design of it. Otherwise we would have just went with straight up text saying "alp", since that is indeed more alp, or maybe even the most alp you can get.

**Comment by lkocman** [comment]
> +1 for image

Jose has a point. If you look at given scale, that particular one is the most easy to recognize. Rest seems to be blurred and details are not easy to spot.

**Comment by lilfrogg** [comment]
> +1 for image

One thing I noticed with that one is that the white top peak is centered over the whole "double mountain". I think centering it over only the left mountain would make more sense.

Also personally, I'm not sure how to feel about the peak of the lower mountain on the right being merged with the base of the peak on the left. I made a mock-up where they are separated, but that also changes the whole balance of the logo, making it look a lot less pyramid-like and symmetrical. Whether that's better or worse is probably up for debate. 
(Also tested out a version with three layers instead of four, but not really sure about that one either)


alpthin1
alpthin2

**Comment by lkocman** [comment]
Oky it's given then. I did ask SUSE Community team to use following logo for the suse.com/c blog post.
alp-community-logo

@hellcp could you please provide an svg version and we'd merge it?

**Comment by hellcp** [comment]
Here you go:
https://gist.github.com/hellcp/af5900b1f58a7528d9da67d4afa76987

**Comment by lilfrogg** [comment]
I'd still suggest aligning the top triangle before that if it isn't planned already. Might throw off the neat-freaks among us quite a bit otherwise. ^^

Am 19. Juli 2022 11:34:00 MESZ schrieb Lubos Kocman ***@***.***>:
>Oky it's given then. I did ask SUSE Community team to use following logo for the suse.com/c blog post.
>alp-community-logo
>
***@***.*** could you please provide an svg version and we'd merge it?

**Comment by hellcp** [comment]
I think even if it's misaligned, it looks more aesthetically pleasing. I have tried a couple of ways to align it over just the left side, and none of them looked good enough to me. Let's just assume that the mountain has a cliff on the right side of the left peak.
Screenshot from 2022-07-19 13-03-54

**Comment by lilfrogg** [comment]
Okay if you tried it out then it's probably better this way. Plus it does probably maintain the basic triangle shape of the whole thing a bit better this way. Ship it then, I say. :-)

**Comment by lkocman** [comment]
> I think even if it's misaligned, it looks more aesthetically pleasing. I have tried a couple of ways to align it over just the left side, and none of them looked good enough to me. Let's just assume that the mountain has a cliff on the right side of the left peak. Screenshot from 2022-07-19 13-03-54

Looks good to me! I also find it more pleasing.

**Comment by bittin** [comment]
@ddemaio is working on this during todays weekly meeting

**Comment by lkocman** [comment]
Actually we were wrong :-) These are the mountains 

les_droites

**Comment by hellcp** [comment]
As with most things in life, it's a matter of perspective

**Pull request merged**
