### PR TITLE
Release-Flyer 15.2 - initial commit

### PR DESCRIPTION
**Pull request by sheimbach**
- changed "System Requirements" to some Kernel info
- added discord icon to "Connect"

### CODE REVIEW

**Comment by sheimbach** [comment]
This is the new flyer for the 15.2 release

**Comment by ddemaio** [comment]
@sheimbach and chance you have the svg of the container png?

**Comment by sheimbach** [comment]
> @sheimbach and chance you have the svg of the container png?

@ddemaio it is a blender rendering. I can rerender it in any resolution you like. But it is not a svg unfortunately.

**Comment by ddemaio** [comment]
Thanks @sheimbach. could you possibly render the Leap 15.2 smaller. It's a little too large for https://twitter.com/openSUSE page. I"ll also try to render it and maybe learn something, but I'm not all to familiar with blender's options.

**Comment by sheimbach** [comment]
@ddemaio I fit the size of the image in gimp and did some basic color correction. You can find the file in this pull request: https://github.com/openSUSE/artwork/pull/44 under social/png
I also added the final export of the flyer for print.

**Comment by ddemaio** [comment]
thank you @sheimbach I really love what you did. A big thank you!

**Pull request merged**
