### PR TITLE
Leap 15.3 recognition

### PR DESCRIPTION
**Pull request by lkocman**
Hello openSUSE Marketing!

It's that time of the year when we're done with release and we'd like to recognize people who made an impact. There are many within openSUSE Marketing team as well!

I'd like to ask you for help with artwork and text regarding recognitions for openSUSE Leap 15.3.

Just a note that this year's box color was yellow! So we should probably project it on recognitions as well.

Any ideas for graphics or perhaps a completely different way of recognizing people, which is highly welcome? Something that can be achieved within the next 14 days or so?

Last's year graphics and email templates can be found here https://github.com/openSUSE/artwork/pull/49

Thank you

Lubos Kocman
openSUSE Leap Release Manager

### CODE REVIEW

**Comment by lkocman** [comment]
recognition_initial

This is how simple bump of 15.2 would look like. We can for sure do better than this.

**Comment by lkocman** [comment]
Incorporating graphics / colors from this year's box would be quite nice! 
[OpenSUSE_Leap_15 3_Box](https://user-images.githubusercontent.com/510119/124192507-b11fdd00-dac5-11eb-91fc-9428911a1d32.png)

**Comment by lkocman** [comment]
banner-you-took-the-leap

Yellow attempt

**Comment by hellcp** [comment]
That's a touch too light and saturated, I would probably go for something darker

**Comment by lkocman** [comment]
Will do @hellcp. I was also thinking of doing the pattern just like on the box. Or do you think than plain color looks better?

**Comment by lkocman** [comment]
Another idea would be to send emails + have a wall of fame with the same text as for emails. 
(Ignore the marquee effect of the box I was just playing with text transformations) :-) 

Simply fade-in/fade-out of text quotes from a local .js file containing json with data for each recognition 

credits

**Comment by ddemaio** [comment]
leap
This is a logo @hellcp made for Leap that can transition us to using it. Not sure if this helps.

**Comment by lkocman** [comment]
@hellcp would you mind if I'd use a monochromatic version of the new leap logo instead?

**Comment by hellcp** [comment]
I'm not sure replacing the logos right now is the right call, considering we just had a release with the old ones, I would use the old logo for now

**Comment by lkocman** [comment]
This one should be merged. We need to re-do this for 15.4 anyway.

**Pull request merged**
