### PR TITLE
Add Leap 16.0 annoucement banner

### PR DESCRIPTION
**Pull request by lkocman**
Simple banner for the announcement article. Handwritten with metallic gold acrylic paint. 

I did cleaned it up in gimp a bit. Also thanks to Doug for comment that I should yellow-up the gold as the original tone + lightning was bit brownish.

The digit 16 is OpenSans as I didn't like number 1 from SourceSans Pro.

leap16_small

### CODE REVIEW

**Comment by lkocman** [comment]
I had original idea to have a metalic paint of just digit "16". I did multiple paintings and I liked this idea the most.

**Comment by lkocman** [comment]
leap16_small

further smoothing of letters

**Comment by hellcp** [comment]
I like it a lot

**Comment by nektarije** [comment]
Slightly edited for more vibrant colours and brightness

leap16-v4

**Comment by lkocman** [comment]
@nektarije I do like your version better.  Let's use that one. @hellcp would you agree?

**Comment by lkocman** [comment]
I can fix that.

**Comment by lkocman** [comment]
@nektarije next time make sure to upload png, as we store png or svg in this repo. I've converted it as png and submitted your version in https://github.com/openSUSE/artwork/pull/79

**Pull request merged**
