### PR TITLE
Initial zypp team logo

### PR DESCRIPTION
**Pull request by lkocman**
* Artwork done by @hellcp
* bgcolor based on the current github openSUSE grey button used by zypp team
zypp-team

### CODE REVIEW

**Comment by hellcp** [comment]
I would run optipng over the png and save as optimized svg in inkscape to optimize that a little bit.

**Comment by lkocman** [comment]
Is this any better @hellcp ? I do have inkscape 1.0.1 which doesn't have png optimization, so I just plaied with available options during export. However the optimized svg was an option.

**Comment by hellcp** [comment]
optipng is a cli tool available in the repos

**Review by hellcp — APPROVED** [review]

**Comment by mlandres** [comment]
I just immediately wondered why the zip goes down (opening a gap, tearing things apart) rather than upwards (closing the gap, fixing things). How would it look the other way round?

**Comment by lkocman** [comment]
up
 This would be the zypp up variant

**Comment by mlandres** [comment]
Team says, the down variant (1st one) looks better.

**Comment by lkocman** [comment]
Merging! Thank you

**Pull request merged**
