### PR TITLE
add hexagon stickers

### PR DESCRIPTION
**Pull request by cho2**
add hexagon stickers:
* openSUSE logo
* Leap logo
* Tumbleweed logo
* geeko

### CODE REVIEW

**Comment by LelCP** [comment]
Finally somebody made those. I would say, margins are a little bit wrong :c 

Give geeko more breathing space (or remove text or something).

With distro logos it's vice versa, they are too small, text is really not that important :c 

If you include text in shareable svg, please turn it into object. Unfortunately previews in most things will show them with different fonts and not intended ones if you don't do that.

**Comment by cho2** [comment]
> If you include text in shareable svg, please turn it into path. Unfortunately previews in most things will show them with different fonts and not intended ones if you don't do that.

For logo with text, i just copied from https://github.com/openSUSE/artwork/tree/master/Logo

**Comment by Dutchglory** [comment]
issues with cloning this branch (master)  see log files for details.
 
[opensuse artwork git issues.log.txt](https://github.com/openSUSE/artwork/files/1958545/opensuse.artwork.git.issues.log.txt)

**Comment by cho2** [comment]
@Dutchglory 
> issues with cloning this branch (master) see log files for details.

Looks like cloning from Windows, so that character `:` on files like `Screenshot from 2013-02-07 11:11:12.png` can't be cloned

**Comment by Dutchglory** [comment]
filename should have windows compatible filenames  or is this for Linux only?

**Comment by cho2** [comment]
Here is the basic idea
photo_2018-04-30_13-14-22

> Text under logos in case of distributions isn't part of the logo, so it can be freely scaled
> We also have ability to use chameleon without text, but with trademark logo only

I'll make another version without text according to https://github.com/openSUSE/artwork/blob/master/Logo/official-logo-geeko-color.png

**Comment by LelCP** [comment]
Leap and TW logos are way too small, their text on the other hand doesn't have to be that big. I like chameleon only versions ;)

**Comment by cho2** [comment]
>Leap and TW logos are way too small, their text on the other hand doesn't have to be that big. I like chameleon only versions ;)

I just copied from https://github.com/openSUSE/artwork/tree/master/Logo/Leap and https://github.com/openSUSE/artwork/tree/master/Logo/Tumbleweed so their proportions are same

**Comment by hellcp** [comment]
Screw those proportions, sticker logo should be visible. Those proportions were made for cases like [these](https://software.opensuse.org/distributions/tumbleweed), and not sticker kind of things (although actually looking at text to logo ratio on that site, it's way closer to sticker size than logo from gh).

**Comment by cho2** [comment]
I'll edit soon

**Comment by DVSB** [comment]
cho2  is this screen images to downloads

**Pull request closed without merging**
